# Dev

trigger:
  branches:
    include:
    - master
    - development

pr:
  branches:
    include:
    - master
    - development
  paths:
    exclude:
    - '*.md'
    - 'docs/*'
    - 'performance/*'
    - '*.png'
    - 'README.md'

name: $(DayOfYear)$(Rev:.r)

variables:
- group: K2Bridge CI-CD - dev
- name: MAJOR_MINOR_VERSION
  value: "0.2" # ONLY UPDATE THIS
- name: SEMANTIC_VERSION
  value: "$(MAJOR_MINOR_VERSION).$(Build.BuildId)"
- name: KUSTO_DB
  value: "build$(Build.BuildId)"
- name: COLLECT_TELEMETRY
  value: false
- name: TELEMETRY_KEY
  value: "00000000-0000-0000-0000-000000000000"
- name: DayOfyear
  value: "DAYREV"
- name: BuildParam
  value: $(DayOfYear)$(Rev:.r)   

steps:
- powershell: $(Build.BuildId) % 100000 # display MyRunNumber
- script: echo $(Build.Repository.Name)
pool:
  vmImage: ubuntu-latest

#stages:
#- template: azure-pipelines.yml
